### ISSUE TITLE
weighted waterfall engine?

### ISSUE THREAD

**Issue by pixelpaulaus** [kessler/node-loadbalance#18]
as per your docs, i though the WeightedRoundRobinEngine would do this, but it doesnt...

Is there an engine to have a pool such as....

[{ object: 'min', weight: 50 }, {object: 'med', weight: 100 }, {object: 'max', weight: 500 }]

where it will run them in order.
So it will do the 50 'min' first, then when done it will move onto do the 100 'med', then the 400 'max'
and when all done, go back to the beginning.

**Comment by kessler** [comment]
@pixelpaulaus 
The test for the WeightedRoundRobinEngine passes and it does exactly what you describe... 
If you want to provide a working code sample I can look into it, but it doesn't seem like there's a problem with that engine.
Please feel free to reopen this issue.
